version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  application:
    build: .
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'phabricator_data:/bitnami/phabricator'
      - 'apache_data:/bitnami/apache'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  phabricator_data:
    driver: local
  apache_data:
    driver: local
